// Code generated by protoc-gen-go-names. DO NOT EDIT.

package proto

// Message names
const (
	User_MESSAGE_NAME = "User"
	Book_MESSAGE_NAME = "Book"
)

// Field names
const (
	Name_FIELD_NAME   = "Name"
	Author_FIELD_NAME = "Author"
)
